version: '3.1'
services:
  zookeeper:
    image: strimzi/kafka:latest-kafka-2.6.0
    container_name: zookeeper
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
  kafka:
    image: strimzi/kafka:latest-kafka-2.6.0
    container_name: kafka
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "29092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:29092,PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgresql:
    container_name: postgres
    hostname: postgres
    image:  docker.io/bitnami/postgresql:13.2.0-debian-10-r11
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pgpwd
      POSTGRESQL_DATABASE: postgres
      BITNAMI_DEBUG: "false"
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/bitnami/postgresql
  transportation:
    image: quay.io/ibmcase/vaccine-transportation
    hostname: transportation
    container_name: transportation
    ports:
      - 8081:8080
    environment:
      TRANSPORTATION_TOPIC: vaccine.transportation
      SCHEMA_REGISTRY_URL: http://localhost:8090
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 
      KAFKA_SSL_TRUSTSTORE_LOCATION: 
      KAFKA_USER:
      KAFKA_SCRAM_PWD:
      QUARKUS_PROFILE: dev
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: alongpassw0rd 
  apicurio: 
    container_name: apicurio
    hostname: apicurio
    image: apicurio/apicurio-registry-mem
    ports:
      - 8090:8080