version: '3.1'
services:
  postgresql:
    container_name: postgres
    hostname: postgres
    image:  docker.io/bitnami/postgresql:13.2.0-debian-10-r11
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pgpwd
      POSTGRESQL_DATABASE: orderdb
      BITNAMI_DEBUG: "false"
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/bitnami/postgresql
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: alongpassw0rd 
